name: Build and Deploy to Testflight

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
 build-deploy-testflight:
   runs-on: macos-14
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Setup Ruby Environment
       uses: ruby/setup-ruby@v1
       with:
         ruby-version: 3.2.2
         bundler-cache: true
     - name: Decode Signing Certificate Into a File
       env:
         CERTIFICATE_BASE64: ${{ secrets.IOS_DIST_SIGNING_KEY }}
       run: |
         echo $CERTIFICATE_BASE64 | base64 --decode > signing-cert.p12
     - name: Switch to Xcode 15.4
       run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer
     - name: Build and Deploy to Testflight
       uses: maierj/fastlane-action@v3.1.0
       with:
        lane: upload_beta_testflight
       env:
         DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
         DEVELOPER_APP_IDENTIFIER: '${{ secrets.DEVELOPER_APP_IDENTIFIER }}'
         DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
         FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
         MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
         GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
         PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
         PROVISIONING_PROFILE_ID: '${{ secrets.PROVISIONING_PROFILE_ID }}'
         TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
         TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
         ASC_KEY_ID: '${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}'
         ASC_ISSUER_ID: '${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}'
         ASC_KEY: '${{ secrets.APP_STORE_CONNECT_API_KEY_CONTENT }}'
